project:
  type: book
  output-dir: _bookpdf

book:
  title: Tinderbox file for Quarto
  subtitle: How to use this file
  author: fryagbye

  page-footer:
    left: |
      footer left
    right: |
      footer right
  chapters:
    - index.qmd
    - usage-environment.qmd
    - setting.qmd
    - make-notes.qmd
    - translate-and-rename-htmlexportfilename.qmd
    - part-in-book-format.qmd
    - cross-reference-using-ziplink.qmd
    - export.qmd
    - restrictions.qmd
    - references.qmd

format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    pdf-engine: lualatex
    code-link: true

    author-meta: "fryagbye"
    indent: true
    include-in-header:
     - text: |
         \usepackage{float}
         \renewcommand{\topfraction}{.85}
         \renewcommand{\bottomfraction}{.7}
         \renewcommand{\textfraction}{.15}
         \renewcommand{\floatpagefraction}{.66}
         \setcounter{topnumber}{3}
         \setcounter{bottomnumber}{3}
         \setcounter{totalnumber}{4}
         \usepackage{calc}
         \usepackage {bxjalipsum}
         \usepackage{pxrubrica}

    callout-appearance: default
    

lang: en

bibliography: citation/references.bib

language: _language.yml

documentclass: bxjsbook
classoption: A4paper,10pt,lualatex,ja=standard,textwidth-limit=50,english
papersize: a4

execute:
  cache: false
  
  freeze: auto

editor: source

