project:
  type: book
  output-dir: _bookhtml

book:
  title: Tinderbox file for Quarto
  author: fryagbye
  reader-mode: true

  page-footer:
    left: |
      footer left
    right: |
      footer right
  cover-image: cover.png
  
  
  repo-url: https://github.com/fryagbye/tinderboxwithquarto
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    pinned: true
  chapters:
    - index.qmd
    - usage-environment.qmd
    - setting.qmd
    - part: Book format
      chapters:
        - make-notes.qmd
        - rename-htmlexportfilename-of-a-note-with-translation.qmd
        - part-in-book-format.qmd
        - cross-reference-using-ziplink.qmd
        - export.qmd
        - example.qmd
    - part: Manuscript format
      chapters:
        - make-manuscript-subproject.qmd
        - export-and-render.qmd
    - part: revealjs format
      chapters:
        - make-sub-project-folder.qmd
    - mermaid-flowchart.qmd
    - graphviz-optional.qmd
    - references.qmd
  appendices:
    - restrictions.qmd

format:
  html:
    theme:
      - cosmo
      
    code-link: true
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    highlight-style: base16-atelier-dune
    link-external-newwindow: true
    pdf-engine: lualatex
    author-meta: "fryagbye"
    indent: true
    include-in-header:
     - text: |
         <link rel="preconnect" href="https://fonts.googleapis.com">
         <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
         <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono:wght@400;700&display=swap" rel="stylesheet">
         <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&family=Noto+Sans+Mono:wght@400;700&display=swap" rel="stylesheet">

    mainfont: "Noto Sans JP"
    monofont: "Noto Sans Mono"
    callout-appearance: default

lightbox:
  match: auto
  effect: zoom
  desc-position: bottom
  loop: true


lang: en
bibliography: /Users/tk4o2ka/github/tinderboxwithquarto/citation/references.bib

language: _language.yml
classoption: fleqn


execute:
  cache: true
  
  freeze: auto
  crossrefs-hover: false	

editor: source

