project:
  type: book
  output-dir: _bookpdf

book:
  title: Tinderbox file for Quarto
  subtitle: How to use this file
  author: fryagbye

  page-footer:
    left: |
      footer left
    right: |
      footer right
  chapters:
    - index.qmd
    - usage-environment.qmd
    - setting.qmd
    - part: Book format
      chapters:
        - make-notes.qmd
        - translate-and-rename.qmd
        - part-in-book-format.qmd
        - cross-reference-using-ziplink.qmd
        - export.qmd
        - example.qmd
    - part: Manuscript format
      chapters:
        - make-sub-project-folder.qmd
        - make-quartoyml.qmd
        - make-notes.qmd
        - export-and-render.qmd
    - mermaid-flowchart.qmd
    - references.qmd
    - restrictions.qmd

format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 3
    pdf-engine: xelatex
    