```{r, echo=FALSE}
#| include: false
out_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
source("_common.R")
```
# Setting {#sec-setting }

1. Setting up with "TBXConfig" note

    You need to change the values of the following "TBXConfig" attributes for configuration.

* `$Indent_Charactor` -> Set the symbol representing the depth of indentation. ( default value = ★ )
* `$ExList` -> List of notes excluded from cross-reference search ( default value = "List and Agent etc" )
* `$ExportFolder` -> Path of exported files. ( for Stamp "Move qmd files" )
* `$ToggleTOC` -> Toggle for Generating TOC. ( default value = false ) You can use quarto option for TOC in _quarto.yml. 
* `$Q_TableOfContainsNote` -> **$Name** of TOC note. ( default value = Table of Contents )
* `$Rename_in` -> Setting for translating a label. ( default value = ja:en )
* `$Q_PDFEngine` -> Setting for [pdf engine](https://quarto.org/docs/output-formats/pdf-engine.html) This file is tested only with lualatex. ( default value = lualatex )
* ~~`$OutlineBaseControl` -> Adjustment of section levels in Markdown. ( default = 1 )~~

     e.g. 
    * $OutlineBaseControl = 0 -> \#\# Title
    
    * $OutlineBaseControl = 1 -> \# Title 

2. Making a `_quarto.yml`

    You can change the values of attributes of the "_quarto" note to change quarto options. The quarto options are attributes that start with "Q" in this file. The initial setting specified in `_quarto.yml` is for Japanese output. Please refer to [Quarto Book Structure](https://quarto.org/docs/books/book-structure.html) and [PDF Basics](https://quarto.org/docs/output-formats/pdf-basics.html) in detail.

    If you use [Custom Translations](https://quarto.org/docs/authoring/language.html#custom-translations), you need to make `$Q_Has_Language_YML` `true` and set `$Q_Language_YML` for the filename.
The "_language" note in this file is for translating to Japanese.

3. Changing the `_common.R` file. ( optional )

    You can set up `knitr` package options for R chunk.  
    


