

# Make sub-project folder {#sec-make-revealjs-subproject }

Make a note for the sub-project with **pSubfolderRevealjs** .






## Front Matter and Subnote



1. pFrontmatterRevealjs

    
    This is a qmd file that contains a Front Matter. When you export, it has descendants' contents.


2. pSubnoteRevealjs

    This is a dummy file for pFrontmatterRevealjs. The markdown level depends on the indent level and `$OutlineBaseControl` of the subproject folder.

```
$OutlineDepthBase * "#" + $OutlineBaseControl(collect(ancestors,$Path)[-1]))
```

 
`$IsRevealjs = true`


3. Quote chunk code blocks

    You can chunk code blocks with a quote tag like the one below from a child note (pRChunk or pPChunk).
    <Lang:chunknotename>
 







## quarto-live extention (β version)

This file supports [quarto-live](https://r-wasm.github.io/quarto-live/).
You add the quarto-live extension to your subproject path.
(If you add it to the project root folder and call it with a relative path, an error will occur.)







## Example


[Example live-revealjs](https://fryagbye.quarto.pub/quarto-presentations/#/title-slide)







