project:
  type: manuscript

manuscript:
  article: "index.qmd"



format:
  pdf:
    number-sections: true
    number-depth: 1
    pdf-engine: lualatex
    fig-format: pdf
    fig-dpi: 300
  html:
    number-sections: true
    number-depth: 1
    comments:
      hypothesis: true
    fig-format: svg
  docx:
    number-sections: true
    number-depth: 1
  jats:
    number-sections: true
    number-depth: 1
    fig-format: png


bibliography: ../citation/references.bib
execute:
  cache: true
  freeze: auto


