---
title: "Quarto Presentations"
subtitle: "Create beautiful interactive slide decks with Reveal.js"



format:
   live-revealjs:
    number-sections: true
    number-depth: 0
    
    css: styles.css
    slide-number: h.v
    
    footer: https://quarto.org/docs/presentations/revealjs/
    scrollable: true
    
    
    transition: convex
    
    

---
{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}






---



## Interactive Editor

You can quote a chunk code block with a tag that has the pChunk child note.  
The language of chunk code is `webr` for R or `pyodide` for python








---



## R chunk example 1



```{r}
#| label: fig-Graph
#| fig-width: 6
#| fig-height: 3
library(ggplot2)
ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")


```










---



## R chunk example 1 ( Warning off option )

If you want to suppress warning messages, you set `$Q_ChunkSuppressWarning` false.


```{webr}
#| warning: false
#| fig-width: 6
#| fig-height: 3

library(ggplot2)
ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess")

```










---



## R chunk example 2



```{r}
#| fig-width: 5
mod <- lm(waiting ~ eruptions, data = faithful)
plot(faithful, main = "Old Faithful Geyser Data")
abline(mod, col = 'blue')
summary(mod)

```










---



## Python chunk example



```{python}
#| echo: true
#| label: fig-python
#| fig-width: 5
import matplotlib.pyplot as plt
import numpy as np

x = np.random.normal(170, 10, 250)
plt.hist(x)
plt.show()
```








